import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import worker from '../worker.mjs';
const payload={inquiry_type:'Buying Property',county:'Indian River',property_type:'Industrial Property',first_name:'Synthetic',last_name:'Test',email:'synthetic@example.invalid',preferred_contact:'Email',rights_acknowledged:true,relationship_acknowledged:true,property_location:'SYNTHETIC LOCATION',timeframe:'Now',owner_status:'No',best_contact_time:'Morning',referral_source:'Other',source_page:'https://fltract.com/contact/'};
function fixture({emailFails=false,insertFails=false}={}){const writes=[];let sends=0;const env={DB:{prepare(sql){return {async first(){return null;},bind(...args){return {async run(){if(insertFails&&sql.includes('INSERT INTO inquiries'))throw Error('synthetic failure');writes.push({sql,args});return {meta:{last_row_id:1}};}};}};}},SEND_EMAIL:{async send(){sends++;if(emailFails)throw Error('synthetic email failure');return {messageId:'synthetic'};}}};return {env,writes,get sends(){return sends;}};}
function request(value=payload,path='/submit'){return new Request('https://replacement.example'+path,{method:'POST',headers:{Origin:'https://fltract.com','Content-Type':'application/json'},body:JSON.stringify(value)});}
test('every inquiry option displayed in form is accepted by replacement',async()=>{const html=readFileSync(new URL('../../../contact/index.html',import.meta.url),'utf8');const select=html.match(/<select name="inquiry_type"[^>]*>(.*?)<\/select>/s)[1];const options=[...select.matchAll(/<option>(.*?)<\/option>/g)].map(m=>m[1]);for(const inquiry_type of options){const f=fixture();assert.equal((await worker.fetch(request({...payload,inquiry_type}),f.env)).status,201,inquiry_type);}});
test('extra intake answers are preserved in existing details field',async()=>{const f=fixture();const response=await worker.fetch(request(),f.env);assert.equal(response.status,201);const row=f.writes.find(w=>w.sql.includes('INSERT INTO inquiries'));assert.match(row.args[11],/Timeframe: Now/);assert.match(row.args[11],/Owner status: No/);assert.match(row.args[11],/Best contact time: Morning/);assert.match(row.args[11],/Referral source: Other/);});
test('phone selection requires explicit live-call permission and valid number',async()=>{for(const extra of [{preferred_contact:'Phone',phone:'7725550100'},{preferred_contact:'Phone',phone:'abc',live_call_opt_in:true}]){const f=fixture();assert.equal((await worker.fetch(request({...payload,...extra}),f.env)).status,400);assert.equal(f.writes.length,0);}const f=fixture();assert.equal((await worker.fetch(request({...payload,preferred_contact:'Phone',phone:'7725550100',live_call_opt_in:true}),f.env)).status,201);});
test('legacy combined consent cannot manufacture two separate acknowledgments',async()=>{const f=fixture();assert.equal((await worker.fetch(request({...payload,rights_acknowledged:false,relationship_acknowledged:false,consent:true}),f.env)).status,400);assert.equal(f.writes.length,0);});
test('new and legacy honeypots both avoid saves and emails',async()=>{for(const name of ['website','company_website']){const f=fixture();assert.equal((await worker.fetch(request({...payload,[name]:'bot'}),f.env)).status,200);assert.equal(f.writes.length,0);assert.equal(f.sends,0);}});
test('malformed and oversized payloads rejected before writing',async()=>{for(const [body,status] of [['null',400],['[]',400],['{',400],[JSON.stringify({details:'x'.repeat(17000)}),413]]){const f=fixture();const response=await worker.fetch(new Request('https://replacement.example/submit',{method:'POST',headers:{'Content-Type':'application/json'},body}),f.env);assert.equal(response.status,status);assert.equal(f.writes.length,0);}});
test('preflight permits matching path and rejects other origins/paths',async()=>{const f=fixture();const preflight=()=>new Request('https://replacement.example/submit',{method:'OPTIONS',headers:{Origin:'https://fltract.com','Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'content-type'}});assert.equal((await worker.fetch(preflight(),f.env)).status,204);assert.equal((await worker.fetch(new Request('https://replacement.example/submit',{method:'OPTIONS',headers:{Origin:'https://evil.example'}}),f.env)).status,403);});
test('email failure preserves successful saved intake; save failure sends no email',async()=>{const f=fixture({emailFails:true});const response=await worker.fetch(request(),f.env);assert.equal(response.status,201);assert.equal((await response.json()).acknowledgment_email,'failed');assert.equal(f.writes.filter(w=>w.sql.includes('INSERT INTO inquiries')).length,1);const bad=fixture({insertFails:true});assert.equal((await worker.fetch(request(),bad.env)).status,500);assert.equal(bad.sends,0);});
test('form points at replacement and exposes separate unchecked consent options',()=>{const html=readFileSync(new URL('../../../contact/index.html',import.meta.url),'utf8');assert.match(html,/fltract-intake-5a25\.b2bconsult4u\.workers\.dev\/submit/);assert.doesNotMatch(html,/payload\.consent=/);assert.doesNotMatch(html,/<option>Text Message<\/option>/);for(const name of ['rights_acknowledged','relationship_acknowledged','live_call_opt_in','marketing_email_opt_in'])assert.match(html,new RegExp('name="'+name+'"'));});
