import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {seedRoles,startSession,authenticate,requirePermission,logout,saveRole,revokeMember,expireSessions,accessLog,startOwnerSupport,assignRole,expireSupportSessions} from '../access.mjs';
import {crmAuthorizer,requireSameOrigin} from '../http.mjs';
const now=1800000000000;
async function fixture(role='employee'){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../migration.sql',import.meta.url),'utf8'));
 const db={prepare(sql){let args=[];return {bind(...a){args=a;return this;},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){return sqlite.prepare(sql).run(...args);}};},async batch(ss){sqlite.exec('BEGIN');try{for(const s of ss)await s.run();sqlite.exec('COMMIT');}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 sqlite.exec("INSERT INTO businesses VALUES('a','A'),('b','B'); INSERT INTO users VALUES('u','provider','subject'),('other','provider','other'),('owner','provider','owner'); INSERT INTO memberships VALUES('a','u',1),('a','other',1),('b','other',1); INSERT INTO platform_owners VALUES('owner',1);");
 await seedRoles(db,'a');await seedRoles(db,'b');sqlite.prepare('INSERT INTO member_roles VALUES(?,?,?)').run('a','u',role);
 sqlite.exec("INSERT INTO resources VALUES('a','client','1','team','u'),('a','client','2','team','other'),('b','client','3',NULL,'other'),('a','inquiry','1','team','u'); INSERT INTO team_members VALUES('a','team','u');");
 const identity={issuer:'provider',subject:'subject'},session=await startSession({db,verifiedIdentity:identity,businessId:'a',now}),token=session.cookie.split(';')[0].split('=')[1];return {db,sqlite,identity,session,token};
}
test('six starter roles; exports denied by default',async()=>{const f=await fixture();assert.equal(f.sqlite.prepare("SELECT count(*) n FROM roles WHERE business_id='a'").get().n,6);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM role_grants WHERE permission LIKE '%.export'").get().n,0);});
test('assigned resource and business isolation',async()=>{const f=await fixture();await requirePermission({...f,permission:'clients.view',resource:{kind:'client',id:'1'},now});for(const id of ['2','3'])await assert.rejects(requirePermission({...f,permission:'clients.view',resource:{kind:'client',id},now}));await assert.rejects(requirePermission({...f,permission:'clients.export',now}));});
test('team permissions and resource type enforced',async()=>{const f=await fixture('manager');await requirePermission({...f,permission:'clients.edit',resource:{kind:'client',id:'2'},now});await assert.rejects(requirePermission({...f,permission:'clients.edit',resource:{kind:'inquiry',id:'1'},now}));f.sqlite.exec('DELETE FROM team_members');await assert.rejects(requirePermission({...f,permission:'clients.view',resource:{kind:'client',id:'2'},now}));});
test('CEO business scope does not include technical administration',async()=>{const f=await fixture('ceo');await requirePermission({...f,permission:'clients.view',resource:{kind:'client',id:'2'},now});await assert.rejects(requirePermission({...f,permission:'users.manage',now}));await assert.rejects(requirePermission({...f,permission:'clients.view',resource:{kind:'client',id:'3'},now}));});
test('hashed token; idempotent logout invalidates session',async()=>{const f=await fixture();assert.notEqual(f.sqlite.prepare('SELECT token_hash FROM sessions').get().token_hash,f.token);await logout({...f,now:now+1});await logout({...f,now:now+2});await assert.rejects(authenticate({...f,now:now+3}));assert.equal(f.sqlite.prepare("SELECT count(*) n FROM access_events WHERE event='logout'").get().n,1);});
test('expiry recorded at actual expiry, not as logout',async()=>{const f=await fixture();await expireSessions(f.db,now+9*3600000);assert.equal(f.sqlite.prepare("SELECT occurred_at FROM access_events WHERE event='expired'").get().occurred_at,now+8*3600000);await assert.rejects(authenticate({...f,now:now+9*3600000}));});
test('membership status immediately enforced',async()=>{const f=await fixture();f.sqlite.exec("UPDATE memberships SET active=0 WHERE business_id='a' AND user_id='u'");await assert.rejects(authenticate({...f,now}),/membership_inactive/);});
test('custom role creation prevents escalation and self changes',async()=>{const f=await fixture('administrator');await saveRole({...f,roleId:'support',name:'Support',grants:[{permission:'audit.view',scope:'business'}],now});await assert.rejects(saveRole({...f,roleId:'thief',name:'Thief',grants:[{permission:'clients.export',scope:'business'}],now}),/grant_escalation/);await assert.rejects(saveRole({...f,roleId:'administrator',name:'Admin',grants:[],now}),/self_role/);});
test('bootstrap preserves customized role grants',async()=>{const f=await fixture();f.sqlite.exec("DELETE FROM role_grants WHERE business_id='a' AND role_id='employee'");await seedRoles(f.db,'a');assert.equal(f.sqlite.prepare("SELECT count(*) n FROM role_grants WHERE business_id='a' AND role_id='employee'").get().n,0);});
test('audit append-only and bounded pagination',async()=>{const f=await fixture('administrator');assert.equal((await accessLog({...f,now})).length,1);assert.throws(()=>f.sqlite.exec('DELETE FROM access_events'),/append-only/);await assert.rejects(accessLog({...f,limit:101,now}));});
test('revocation isolated to one business',async()=>{const f=await fixture('administrator');await revokeMember({...f,userId:'other',now});assert.equal(f.sqlite.prepare("SELECT active FROM memberships WHERE business_id='b' AND user_id='other'").get().active,1);});
test('owner support requires fresh MFA, restores admin and expires',async()=>{const f=await fixture(),identity={issuer:'provider',subject:'owner',mfaVerified:true,authenticatedAt:now};await assert.rejects(startOwnerSupport({...f,verifiedIdentity:{...identity,mfaVerified:false},businessId:'a',reason:'Repair staff access',now}));const s=await startOwnerSupport({...f,verifiedIdentity:identity,businessId:'a',reason:'Repair staff access',now}),token=s.cookie.split(';')[0].split('=')[1];await assignRole({...f,token,userId:'other',roleId:'administrator',now});await assert.rejects(requirePermission({...f,token,permission:'clients.export',now}));await expireSupportSessions(f.db,now+1800001);await assert.rejects(authenticate({...f,token,now:now+1800001}));assert.equal(f.sqlite.prepare("SELECT count(*) n FROM access_events WHERE event='support_expired'").get().n,1);});
test('customer admin cannot impersonate owner',async()=>{const f=await fixture('administrator');await assert.rejects(startOwnerSupport({...f,verifiedIdentity:{...f.identity,mfaVerified:true,authenticatedAt:now},businessId:'a',reason:'Repair staff access',now}),/platform_owner/);});
test('private card adapter and same-origin mutations',async()=>{const f=await fixture(),request=new Request('https://admin.example.test/account',{headers:{Cookie:f.session.cookie.split(';')[0]}}),allow=crmAuthorizer({request,db:f.db,permission:'reports.view',kind:'inquiry',now});assert.equal(await allow(1),true);assert.equal(await allow(2),false);assert.throws(()=>requireSameOrigin(new Request('https://admin.example.test/update',{method:'POST',headers:{Origin:'https://evil.example'}}),'https://admin.example.test'),/origin_denied/);});
test('login audit and session creation atomic',async()=>{const f=await fixture();f.sqlite.exec("CREATE TRIGGER block_login BEFORE INSERT ON access_events WHEN NEW.event='login' BEGIN SELECT RAISE(ABORT,'test'); END;");await assert.rejects(startSession({...f,verifiedIdentity:f.identity,businessId:'a',now}));assert.equal(f.sqlite.prepare('SELECT count(*) n FROM sessions').get().n,1);});
